name: Docker
on:
  - push
  - pull_request
env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Docker
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Poke config
      run: |
        cp config/example.storage.yml config/storage.yml
        cp config/docker.database.yml config/database.yml
        touch config/settings.local.yml
        
    - name: Build Docker Image
      run: |
        docker compose build
    - name: Start Docker Compose
      run: |
        docker compose up -d
        sleep 15 # let the DB warm up a little
    - name: Prepare Database
      run: |
        docker compose run --rm web bundle exec rails db:migrate
        docker compose run --rm web bundle exec rails i18n:js:export
        docker compose run --rm web bundle exec rails assets:precompile
        docker compose run --rm web osmosis --rx docker/null-island.osm.xml --wd host=db database=openstreetmap user=openstreetmap password=openstreetmap validateSchemaVersion=no
    - name: Test Basic Website
      run: |
        curl -siL http://127.0.0.1:3000 | egrep '^HTTP/1.1 200 OK'
        curl -siL http://127.0.0.1:3000 | grep 'OpenStreetMap is the free wiki world map'
        curl -siL http://127.0.0.1:3000/api/0.6/node/1 | grep 'Null Island'
    - name: Build and push image Aliyun
      run: |
        docker version
        # 登录阿里云镜像仓库
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        # 推送镜像到镜像仓库
        new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/oepnstreetmap-website"
        docker push $new_image
        echo "docker push $new_image"
